language: node_js
cache:
  directories:
    - node_modules

matrix:
  include:
  - node_js: '4'
  - node_js: '5'
  - node_js: '6'
  - node_js: '7'

before_script:
- npm run lint

script:
- npm run build
- npm test