language: node_js
cache:
  directories:
    - node_modules

matrix:
  include:
  - node_js: '6'
  - node_js: '7'
  - node_js: '8'
  - node_js: '9'
  - node_js: '10'

before_script:
- npm run lint

script:
- npm run build
- npm test